<form action="http://doini.com/Task/addMulti/<?php echo $this->viewData['project']['ID']; ?>"
    method="post"  enctype="multipart/form-data"
class="absolute top-1/2 left-1/2 translate-y-[-50%] translate-x-[-50%] w-1/3  bg-primary rounded-md drop-shadow-2xl hidden flex-col space-y-8 px-6 py-8 items-center  min-w-[280px]" id="add-multi-task-form">
<svg  class="close-form  absolute top-0 right-1 cursor-pointer" width="36" height="36" fill="#eef2ff" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="m12 10.583 4.95-4.95 1.414 1.414-4.95 4.95 4.95 4.95-1.414 1.414L12 13.41l-4.95 4.95-1.414-1.414 4.95-4.95-4.95-4.95L7.05 5.633l4.95 4.95Z"></path>
            </svg>
            <div class="flex space-x-2 flex-col md:flex-row items-center border-b border-light fixed top-0">
                <h2 class="text-xl font-semibold text-dark text-center">Add Multi tasks</h2>
                <img id="add-multi" class="cursor-pointer" src="/assets/images/add.svg" alt="add form">
            </div>
            <div id="container" class="flex flex-col gap-5 p-2 overflow-auto max-h-[500px] mt-3">
            </div>
            <input type="submit"  name="addTasks" value="add"
                class="w-20  h-14 bg-dark rounded-full  focus:outline-none
                px-4 focus:border-2 text-indigo-50 font-bold md:w-18 cursor-pointer"> 
            </div>
</form>