<form action="http://doini.com/project/add/<?php echo $_SESSION['user-id']; ?>/" method="post" id="add-project-form"
class="absolute top-1/2 left-1/2 translate-y-[-50%] translate-x-[-50%] w-1/3 h-44 bg-primary rounded-md drop-shadow-2xl hidden flex-col space-y-8">
            <svg  class="close-form absolute top-0 right-1 cursor-pointer" width="36" height="36" fill="#eef2ff" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="m12 10.583 4.95-4.95 1.414 1.414-4.95 4.95 4.95 4.95-1.414 1.414L12 13.41l-4.95 4.95-1.414-1.414 4.95-4.95-4.95-4.95L7.05 5.633l4.95 4.95Z"></path>
            </svg>
            <h2 class="text-xl font-semibold text-dark text-center mt-2">Add project</h2>
            <div class="flex justify-center items-center justify-evenly">
                <input type="text"  name="name" placeholder="Enter project name"
                class="w-56  h-14 bg-indigo-50 rounded-full border border-primary focus:outline-none
                px-4 focus:border-2 text-dark">
                <input type="submit"  name="add" value="add"
                class="w-20  h-14 bg-dark rounded-full  focus:outline-none
                px-4 focus:border-2 text-indigo-50 font-bold md:w-18 cursor-pointer"> 
            </div>
</form>
